version: '3.4'
x-logging:
 logging: &rotate_logging
  driver: "json-file"
  options:
   max-file: "10"
   max-size: "10m"
services:
 time_out:
   profiles: ["cassandra_single_cluster"]
   container_name: time_out
   command: /bin/bash -c "if [ ! -f already.txt ]; then echo 'loading, timeout..'; sleep 2m; touch already.txt; fi"
   image: ${DOCKER_REGISTRY}com/gsi/apu/elastic-similarity/cassandra:${DOCKER_VERSION:-latest}
 dataset-converter:
   profiles: ["cassandra_single_cluster"]
   environment:
    - CASSANDRA_HOSTS=cassandra,node3
    - CASSANDRA_PORT=9042,9044
   depends_on:
    cassandra:
      condition: service_started
    node2:
      condition: service_started
    node3:
      condition: service_started
    time_out:
      condition: service_completed_successfully
 dataset-manager:
   profiles: ["cassandra_single_cluster"]
   environment:
    - CASSANDRA_REPLICATION_FACTOR=1
    - CASSANDRA_POINTS=cassandra,node3
    - CASSANDRA_PORT=9042,9044
   depends_on:
    postgresql:
      condition: service_started
    broker:
      condition: service_started
    redis:
      condition: service_started
    settings-manager:
      condition: service_started
    python-float32-neural:
      condition: service_started
    dataset-converter:
      condition: service_started
    search:
      condition: service_started
    cassandra:
      condition: service_started
    node2:
      condition: service_started
    node3:
      condition: service_started
    time_out:
      condition: service_completed_successfully
 node2:
  container_name: cassandra_node2
  hostname: node2
  profiles: ["cassandra_single_cluster"]
  environment:
   - CASSANDRA_SEEDS=cassandra
   - CASSANDRA_BROADCAST_ADDRESS=node2
   - CASSANDRA_NATIVE_TRANSPORT_PORT=9043
   - CASSANDRA_CLUSTER_NAME=gsi-cluster
   - CASSANDRA_START_RPC=false
   - CASSANDRA_DC=DC1
   - CASSANDRA_RACK=RAC1
   - CASSANDRA_NUM_TOKENS=256
   - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
  ports:
   - 9043:9043
   - 7072:7070
  expose:
   - 9043
   - 7000
   - 7001
   - 7199
   - 9142
   - 9160
  security_opt:
   - seccomp:unconfined
  ulimits:
   memlock: -1
   nproc: 32768
   nofile: 100000
  networks:
   - elastic-similarity
  image: ${DOCKER_REGISTRY}com/gsi/apu/elastic-similarity/cassandra:${DOCKER_VERSION:-latest}
  volumes:
   - /home/public/elastic-similarity/cassandra2:/var/lib/cassandra
  logging:
   <<: *rotate_logging
  depends_on:
   - cassandra
 node3:
  container_name: cassandra_node3
  hostname: node3
  profiles: ["cassandra_single_cluster"]
  environment:
   - CASSANDRA_SEEDS=cassandra,node3
   - CASSANDRA_BROADCAST_ADDRESS=node3
   - CASSANDRA_NATIVE_TRANSPORT_PORT=9044
   - CASSANDRA_CLUSTER_NAME=gsi-cluster
   - CASSANDRA_START_RPC=false
   - CASSANDRA_DC=DC1
   - CASSANDRA_RACK=RAC1
   - CASSANDRA_NUM_TOKENS=256
   - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
  ports:
   - 9044:9044
   - 7073:7070
  expose:
   - 9044
   - 7000
   - 7001
   - 7199
   - 9142
   - 9160
  security_opt:
   - seccomp:unconfined
  ulimits:
   memlock: -1
   nproc: 32768
   nofile: 100000
  networks:
   - elastic-similarity
  image: ${DOCKER_REGISTRY}com/gsi/apu/elastic-similarity/cassandra:${DOCKER_VERSION:-latest}
  volumes:
   - /home/public/elastic-similarity/cassandra3:/var/lib/cassandra
  logging:
   <<: *rotate_logging
  depends_on:
   - cassandra
