version: '3.4'
x-logging:
  logging: &rotate_logging
    driver: "json-file"
    options:
      max-file: "10"
      max-size: "10m"
services:
 broker:
   image: confluentinc/cp-kafka:${CONFLUENT_KAFKA_VERSION}
   container_name: broker
   expose:
    - 29092
   ports:
    - 9093:9093
    - 9092:9092
    - 9101:9101
    - 29092:29092
   volumes:
    - /home/public/elastic-similarity/kafka:/bitnami/kafka
    - /tmp:/tmp
   environment:
    - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
    - KAFKA_JMX_PORT=9101
    - KAFKA_PROCESS_ROLES=broker,controller
    - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
    - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,INNER://:29092
    - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INNER:PLAINTEXT
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${BROKER_HOST}:9092,INNER://broker:29092
    - KAFKA_NODE_ID=1
    - KAFKA_CONTROLLER_QUORUM_VOTERS=1@broker:9093
    - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
    - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    - KAFKA_PROCESS_ROLES=controller,broker
    - KAFKA_LOG_DIRS=/tmp/kraft-combined-logs
    - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    - KAFKA_METADATA_MAX_IDLE_INTERVAL_MS=0
    - CLUSTER_ID=Y9ZDpMcDQtysyA08316InQ
   logging:
     <<: *rotate_logging
   restart: unless-stopped      
   networks:
     - elastic-similarity
 kafka-create-topics:
   image: confluentinc/cp-kafka:${CONFLUENT_KAFKA_VERSION}
   container_name: create-topics
   depends_on:
    - broker
   command: |
     bash -c 'echo Waiting for kafka to be ready ... && \
     sleep 10 && \
     cub kafka-ready -b broker:29092 1 20 && \
     kafka-topics --bootstrap-server=broker:29092 --create --topic setup-vectors --partitions 1 --replication-factor 1 --if-not-exists && \
     kafka-topics --bootstrap-server=broker:29092 --create --topic live-vectors --partitions 1 --replication-factor 1 --if-not-exists && \
     kafka-topics --bootstrap-server=broker:29092 --create --topic actions-topic --partitions 1 --replication-factor 1 --if-not-exists && \
     kafka-topics --bootstrap-server=broker:29092 --create --topic plugin-operations --partitions 1 --replication-factor 1 --if-not-exists && \
     kafka-topics --bootstrap-server=broker:29092 --create --topic heavy-topic --partitions 1 --replication-factor 1 --if-not-exists && \
     exit'
   environment:
     KAFKA_BROKER_ID: ignored
     KAFKA_ZOOKEEPER_CONNECT: ignored
   logging:
     <<: *rotate_logging      
   networks:
     - elastic-similarity

networks:
 elastic-similarity:
  name: elastic-similarity
