version: '3.7'

services:
  qdrant_bench:
    image: qdrant/qdrant:v1.1.0
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-file: 1
        max-size: 15m
    deploy:
      resources:
        limits:
          memory: 100Gb
